# Generated by Django 5.1.1 on 2024-10-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djlearn', '0002_person_created_at_person_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
