# Generated by Django 5.1.1 on 2024-10-20 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djlearn', '0006_rename_name_person_first_name_alter_person_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('net_worth', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner_family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('net_worth', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('net_worth', models.BigIntegerField()),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djlearn.holding')),
            ],
        ),
        migrations.AddField(
            model_name='holding',
            name='owner_family',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='djlearn.owner_family'),
        ),
    ]
