# Generated by Django 5.1.1 on 2024-10-20 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djlearn', '0007_holding_owner_family_company_holding_owner_family'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Owner_family',
            new_name='OwnerFamily',
        ),
    ]
