# Generated by Django 5.1.1 on 2024-10-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djlearn', '0008_rename_owner_family_ownerfamily'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='ownerfamily',
            options={'verbose_name_plural': 'owner families'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'people'},
        ),
    ]
